site_name: Homelab Documentation
site_description: 'This is my homelab documentation that includes pretty much everything to do with my current lab.'
site_author: 'thesyntaxslinger'
site_url: 'https://syntaxslinger.com/'

repo_name: 'syntaxslinger.com'
repo_url: 'https://github.com/thesyntaxslinger/syntaxslinger.com'


theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'Introduction': index.md
  - 'Hypervisor':
    - 'Overview': hypervisor/overview.md
    - 'Storage Setup': hypervisor/storage-setup.md
    - 'Backups': hypervisor/backups.md
    - 'Networking': hypervisor/networking.md
  - 'Administration':
    - 'Bootstrapping': administration/bootstrapping.md
    - 'Updates and Patch Management': administration/updates-and-patch-management.md
