site_name: Homelab Documentation
site_description: 'This is my homelab documentation that includes pretty much everything to do with my current lab.'
site_author: 'thesyntaxslinger'

repo_name: 'syntaxslinger.com'
repo_url: 'https://github.com/thesyntaxslinger/syntaxslinger.com'


theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Introduction': introduction.md
  - 'Hypervisor':
    - 'Overview': hypervisor/overview.md
    - 'Storage Setup': hypervisor/storage-setup.md
    - 'Backups': hypervisor/backups.md
